version: 2.1

parameters:
  resource_class:
    type: enum
    default: "haripofficial/parallel"
    enum: ["small", "medium", "large", "haripofficial/parallel"]

jobs:
  test:
    docker:
      - image: circleci/node:14
    resource_class: << pipeline.parameters.resource_class >>
    parallelism: 3
    steps:
      - checkout

      # Install dependencies
      - run:
          name: Install dependencies
          command: npm install

      # Run tests in parallel
      - run:
          name: Run tests in parallel
          command: npm test

workflows:
  version: 2
  build:
    jobs:
      - test
      # - run_tests:
      #     requires:
      #       - install_dependencies

