version: 2.1

jobs:
  install_dependencies:
    docker:
      - image: circleci/node:14
    resource_class: haripofficial/parallel
    steps:
      - checkout

      # Install dependencies
      - run:
          name: Install dependencies
          command: npm install

  run_tests:
    docker:
      - image: circleci/node:14
    resource_class: haripofficial/parallel
    parallelism: 5

    steps:
      - checkout

      # Restore dependencies
      - attach_workspace:
          at: /root/project

      # Run tests in parallel
      - run:
          name: Run tests in parallel
          command: npm test

workflows:
  version: 2
  build:
    jobs:
      - install_dependencies
      - run_tests:
          requires:
            - install_dependencies

