version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:14
    resource_class: haripofficial/parallel
    parallelism: 1
    steps:
      - checkout

      # Install dependencies
      - run:
          name: Install dependencies
          command: npm install

      # Run tests in parallel
      - run:
          name: Run tests in parallel
          command: npm test

workflows:
  version: 2
  build:
    jobs:
      - test
      # - run_tests:
      #     requires:
      #       - install_dependencies

