version: 2.1

parameters:
  resource_class:
    type: enum
    default: "haripofficial/parallel"
    enum: ["small", "medium", "large", "haripofficial/parallel"]
  parallelism:
    type: integer
    default: 15
  tags:
    type: enum
    default: "@Regression"
    enum: ["@Regression", "@SmokeTest"]

orbs: 
  cypress: cypress-io/cypress@2.0.0
executors:
  with-chrome:
    docker:
      - image: 'cypress/browsers:node16.14.0-chrome99-ff97'
    resource_class: << pipeline.parameters.resource_class >>
      
workflows:
  build:
    jobs:
      - cypress/run:
          executor: with-chrome
          browser: chrome
          parallelism: << pipeline.parameters.parallelism >>
          timeout: 90m
          command: npm install && npm test


